[build]
  command = "npm run build"
  functions = ".lambdas"
  publish = "public"
  environment
    GOOGLE_ANALYTICS_TRACKING_ID = $GOOGLE_ANALYTICS_TRACKING_ID$
    GOOGLE_CREDENTIALS = $GOOGLE_CREDENTIALS$
    GATSBY_GRAPHCMS_ENDPOINT = $GATSBY_GRAPHCMS_ENDPOINT$
    GATSBY_GRAPHCMS_TOKEN = $GATSBY_GRAPHCMS_TOKEN$